{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mock-stripe.serviceAccountName" . }}
  labels:
{{ include "mock-stripe.labels" . | nindent 4 }}
{{- end -}}
