apiVersion: v1
kind: Service
metadata:
  # name: {{ include "mock-stripe.fullname" . }}
  name: {{ .Release.Name }}
  labels:
    {{- include "mock-stripe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mock-stripe.selectorLabels" . | nindent 4 }}
